
project_id = "vxculagfrbvxdtwscjfm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.document-processor]
verify_jwt = true

[functions.store-secret]
verify_jwt = true
