
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxculagfrbvxdtwscjfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4Y3VsYWdmcmJ2eGR0d3NjamZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzE0ODIsImV4cCI6MjA2NDYwNzQ4Mn0.RyBjeZh4TkP6C8EdojURUJXGhlgJelRR9aUzs_z7Rhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
